name: checkm2_checkm2predict
description: CheckM2 provides a set of tools for assessing the quality of genomes recovered metagenomes using machine learning.
keywords:
  - checkm2
  - mag
  - metagenome
  - quality
  - isolates
  - microbes
  - single cells
  - completeness
  - contamination
  - bins
  - genome bins
tools:
  - "checkm2":
      description: "CheckM2 - Predicting the quality of metagenome-recovered bins"
      homepage: "https://github.com/chklovski/CheckM2"
      documentation: "https://github.com/chklovski/CheckM2"
      tool_dev_url: "https://github.com/chklovski/CheckM2"
      doi: "10.1038/s41592-023-01940-w"
      licence: "['GPL v3']"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - db_file:
      type: file
      description: external DIAMOND database, often called `uniref100.KO.1.dmnd`.
      pattern: "*.{dmnd}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - quality_report:
      type: file
      description: File with quality report
      pattern: "*.{tsv}"
  - diamond:
      type: file
      description: Diamond
      pattern: "*.{tsv}"
  - protein:
      type: file
      description: Protein
      pattern: "*.{faa}"

authors:
  - "@willros"
